# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: wcomp
author: Rafael Mudafort
# logo: logo.png

execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# bibtex_bibfiles:
#   - references.bib

repository:
  url: https://github.com/rafmudaf/wcomp
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  google_analytics_id: G-7LZJG24QM5

sphinx:
  mermaid_version: 10.7.0
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.viewcode'
  # - 'sphinx_autodoc_typehints'
  # - 'sphinxcontrib.autoyaml'
  - 'sphinx.ext.napoleon'           # Formats docstring for Google and NumPy style, https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
  - 'sphinxcontrib.mermaid'         # https://sphinxcontrib-mermaid-demo.readthedocs.io/en/latest/

  config:
    # html_theme: sphinx_book_theme
    # templates_path:
    # - '_templates'
    language: 'python'
    nb_execution_show_tb: true          # Shows the stack trace in stdout; its suppressed otherwise.
    nb_execution_raise_on_error: true   # Stops the Sphinx build if there is an error in a notebook. See https://github.com/executablebooks/jupyter-book/issues/2011
    # suppress_warnings:
    # - etoc.toctree                      # autodoc output contains toctrees, so suppress this warning. See https://github.com/executablebooks/sphinx-external-toc/issues/36
    # autoyaml_level: 3
    autosummary_generate: true          # autosummary generates files that contain autodoc directives to automatically create the api docs pages

    # Autodoc config reference
    # https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration
    autodoc_default_options:
      members: true
      member-order: bysource
      undoc-members: true
      private-members: false
      # special-members: true
      special-members': __init__

      # inherited-members
      # show-inheritance
      # ignore-module-all
      # imported-members: true
      # exclude-members
      # class-doc-from
      # no-value
    autodoc_typehints: both
    # mermaid_output_format: png
    mermaid_version: 10.9.0
    # napoleon_use_admonition_for_examples: true