name: deploy-pages

on:
  push:
    # branches:
    # - develop
    # paths:
    # - docs/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        git clone https://github.com/rafmudaf/PyWake
        git clone https://github.com/rafmudaf/foxes
        pip install -e PyWake
        pip install -e foxes
        pip install -e ".[docs]"

    # Generate any required diagrams
    - name: Make diagrams
      working-directory: ${{runner.workspace}}/wcomp/wcomp
      run: |
        pyreverse base_interface.py -c WCompBase -o mmd

    # Build the book
    - name: Build the book
      working-directory: ${{runner.workspace}}/wcomp/docs/
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
